#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>

typedef struct inputGro
{
	int sino;
	float x, y, z;
	char name[10];
} INPUT_GRO;

int findNAtoms (FILE *input)
{
	int nAtoms;
	rewind (input);
	char lineString[1000];

	fgets (lineString, 1000, input);
	fgets (lineString, 1000, input);
	sscanf (lineString, "%d", &nAtoms);

	rewind (input);
	return nAtoms;
}

int computeNTimeframes (FILE *input, char identifier[])
{
	rewind (input);
	int nFrames = 0;
	char lineString[3000];

	printf("Calculating the total number of timeframes...\n");

	while (fgets (lineString, 3000, input) != NULL)
	{
		if (strstr (lineString, identifier))
		{
			nFrames++;
		}
	}

	printf("Number of identified timeframes: %d...\n", nFrames);

	rewind (input);
	return nFrames;
}

INPUT_GRO *readInputCoordinates (INPUT_GRO *inputCoordinates, FILE *input, int nAtoms)
{
	char lineString[3000];

	fgets (lineString, 3000, input);
	fgets (lineString, 3000, input);

	for (int i = 0; i < nAtoms; ++i)
	{
		fgets (lineString, 3000, input);
		sscanf (lineString, "%*s %s %d %f %f %f\n", &inputCoordinates[i].name, &inputCoordinates[i].sino, &inputCoordinates[i].x, &inputCoordinates[i].y, &inputCoordinates[i].z);
	}

	fgets (lineString, 3000, input);

	return inputCoordinates;
}

int computeCondensedIons (INPUT_GRO *inputCoordinates, int nAtoms, char identifier[], float cutoff)
{
	int nCondensed = 0;
	int denom = 0;
	float distance;

	for (int i = 0; i < nAtoms; ++i)
	{
		if (strstr (inputCoordinates[i].name, identifier))
		{
			denom++;
			for (int j = 0; j < nAtoms; ++j)
			{
				distance = sqrt (((inputCoordinates[i].x - inputCoordinates[j].x) * (inputCoordinates[i].x - inputCoordinates[j].x)) + ((inputCoordinates[i].y - inputCoordinates[j].y) * (inputCoordinates[i].y - inputCoordinates[j].y)) + ((inputCoordinates[i].z - inputCoordinates[j].z) * (inputCoordinates[i].z - inputCoordinates[j].z)));

				if (distance < cutoff)
				{
					nCondensed++;
				}
			}
		}	
	}

	nCondensed /= denom;

	return nCondensed;
}

int main(int argc, char const *argv[])
{
	if (argc != 4)
	{
		printf("REQUIRED ARGUMENTS:\n~~~~~~~~~~~~~~~~~~\n\n{~} argv[0] = ./program\n{~} argv[1] = input *.gro file\n{~} argv[2] = output filename\n{~} argv[3] = cutoff distance between O and Na\n{~} argv[4] = cutoff distance between N and Na\n\n");
		exit (1);
	}

	FILE *input, *output;
	input = fopen (argv[1], "r");
	output = fopen (argv[2], "w");
	float cutoff_O = atof (argv[3]), cutoff_N = atof (argv[4]);

	INPUT_GRO *inputCoordinates;
	int nAtoms = findNAtoms (input), checking = fgetc (input), nFrames = computeNTimeframes (input, "Generated by trjconv");
	inputCoordinates = (INPUT_GRO *) malloc (nAtoms * sizeof (INPUT_GRO));

	int *condensed_Na_on_O, *condensed_Na_on_N;
	float avg_condensed_Na_on_O = 0, avg_condensed_Na_on_N = 0, stdev_condensed_Na_on_O = 0, stdev_condensed_Na_on_N = 0;

	condensed_Na_on_O = (int *) calloc (nFrames, sizeof (int));
	condensed_Na_on_N = (int *) calloc (nFrames, sizeof (int));

	int currentTimeframe = 0;

	while (checking != EOF)
	{
		inputCoordinates = readInputCoordinates (inputCoordinates, input, nAtoms);

		condensed_Na_on_O[currentTimeframe] = computeCondensedIons (inputCoordinates, nAtoms, "O", cutoff_O);
		condensed_Na_on_N[currentTimeframe] = computeCondensedIons (inputCoordinates, nAtoms, "N", cutoff_N);

		currentTimeframe++;
		checking = fgetc (input);
	}

	// Calculating average
	for (int i = 0; i < nFrames; ++i)
	{
		avg_condensed_Na_on_O += condensed_Na_on_O[i];
		avg_condensed_Na_on_N += condensed_Na_on_N[i];
	}

	avg_condensed_Na_on_N /= nFrames;
	avg_condensed_Na_on_O /= nFrames;

	// Calculating standard deviation
	for (int i = 0; i < nFrames; ++i)
	{
		stdev_condensed_Na_on_O += ((condensed_Na_on_O[i] - avg_condensed_Na_on_O) * (condensed_Na_on_O[i] - avg_condensed_Na_on_O));
		stdev_condensed_Na_on_N += ((condensed_Na_on_N[i] - avg_condensed_Na_on_N) * (condensed_Na_on_N[i] - avg_condensed_Na_on_N));
	}

	stdev_condensed_Na_on_O /= nFrames;
	stdev_condensed_Na_on_N /= nFrames;

	stdev_condensed_Na_on_O = sqrt (stdev_condensed_Na_on_O);
	stdev_condensed_Na_on_N = sqrt (stdev_condensed_Na_on_N);

	printf("\n\nAverage condensation:\n~~~~~~~~~~~~~~~~~~~~\nNa on N: %f (stdev: %f)\nNa on O: %f (stdev: %f)\n", avg_condensed_Na_on_N, stdev_condensed_Na_on_N, avg_condensed_Na_on_O, stdev_condensed_Na_on_O);

	fprintf(output, "\n\nAverage condensation:\n~~~~~~~~~~~~~~~~~~~~\nNa on N: %f (stdev: %f)\nNa on O: %f (stdev: %f)\n", avg_condensed_Na_on_N, stdev_condensed_Na_on_N, avg_condensed_Na_on_O, stdev_condensed_Na_on_O);

	fclose (input);
	fclose (output);
	return 0;
}