all:
        ###################
        # AVAILABLE OPTIONS
        ###################
	# 1. Type 'make compile' to compile the code
	# 2. Type 'make run' to run the code.
compile:
	gcc -o modifyHamiltonian modifyHamiltonian.c -lm -Wall -fstack-protector
run:
	mkdir nRep80/H_0.991264
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.991264/ffbonded.itp nRep80/H_0.991264/ffnonbonded.itp nRep80/H_0.991264/topol.top 0.991264 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.982605
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.982605/ffbonded.itp nRep80/H_0.982605/ffnonbonded.itp nRep80/H_0.982605/topol.top 0.982605 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.974021
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.974021/ffbonded.itp nRep80/H_0.974021/ffnonbonded.itp nRep80/H_0.974021/topol.top 0.974021 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.965513
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.965513/ffbonded.itp nRep80/H_0.965513/ffnonbonded.itp nRep80/H_0.965513/topol.top 0.965513 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.957078
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.957078/ffbonded.itp nRep80/H_0.957078/ffnonbonded.itp nRep80/H_0.957078/topol.top 0.957078 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.948718
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.948718/ffbonded.itp nRep80/H_0.948718/ffnonbonded.itp nRep80/H_0.948718/topol.top 0.948718 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.94043
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.94043/ffbonded.itp nRep80/H_0.94043/ffnonbonded.itp nRep80/H_0.94043/topol.top 0.94043 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.932215
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.932215/ffbonded.itp nRep80/H_0.932215/ffnonbonded.itp nRep80/H_0.932215/topol.top 0.932215 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.924071
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.924071/ffbonded.itp nRep80/H_0.924071/ffnonbonded.itp nRep80/H_0.924071/topol.top 0.924071 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.915999
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.915999/ffbonded.itp nRep80/H_0.915999/ffnonbonded.itp nRep80/H_0.915999/topol.top 0.915999 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.907997
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.907997/ffbonded.itp nRep80/H_0.907997/ffnonbonded.itp nRep80/H_0.907997/topol.top 0.907997 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.900065
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.900065/ffbonded.itp nRep80/H_0.900065/ffnonbonded.itp nRep80/H_0.900065/topol.top 0.900065 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.892202
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.892202/ffbonded.itp nRep80/H_0.892202/ffnonbonded.itp nRep80/H_0.892202/topol.top 0.892202 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.884409
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.884409/ffbonded.itp nRep80/H_0.884409/ffnonbonded.itp nRep80/H_0.884409/topol.top 0.884409 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.876683
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.876683/ffbonded.itp nRep80/H_0.876683/ffnonbonded.itp nRep80/H_0.876683/topol.top 0.876683 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.869024
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.869024/ffbonded.itp nRep80/H_0.869024/ffnonbonded.itp nRep80/H_0.869024/topol.top 0.869024 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.861433
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.861433/ffbonded.itp nRep80/H_0.861433/ffnonbonded.itp nRep80/H_0.861433/topol.top 0.861433 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.853908
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.853908/ffbonded.itp nRep80/H_0.853908/ffnonbonded.itp nRep80/H_0.853908/topol.top 0.853908 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.846448
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.846448/ffbonded.itp nRep80/H_0.846448/ffnonbonded.itp nRep80/H_0.846448/topol.top 0.846448 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.839054
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.839054/ffbonded.itp nRep80/H_0.839054/ffnonbonded.itp nRep80/H_0.839054/topol.top 0.839054 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.831724
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.831724/ffbonded.itp nRep80/H_0.831724/ffnonbonded.itp nRep80/H_0.831724/topol.top 0.831724 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.824459
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.824459/ffbonded.itp nRep80/H_0.824459/ffnonbonded.itp nRep80/H_0.824459/topol.top 0.824459 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.817256
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.817256/ffbonded.itp nRep80/H_0.817256/ffnonbonded.itp nRep80/H_0.817256/topol.top 0.817256 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.810117
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.810117/ffbonded.itp nRep80/H_0.810117/ffnonbonded.itp nRep80/H_0.810117/topol.top 0.810117 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.80304
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.80304/ffbonded.itp nRep80/H_0.80304/ffnonbonded.itp nRep80/H_0.80304/topol.top 0.80304 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.796025
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.796025/ffbonded.itp nRep80/H_0.796025/ffnonbonded.itp nRep80/H_0.796025/topol.top 0.796025 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.789071
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.789071/ffbonded.itp nRep80/H_0.789071/ffnonbonded.itp nRep80/H_0.789071/topol.top 0.789071 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.782178
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.782178/ffbonded.itp nRep80/H_0.782178/ffnonbonded.itp nRep80/H_0.782178/topol.top 0.782178 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.775346
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.775346/ffbonded.itp nRep80/H_0.775346/ffnonbonded.itp nRep80/H_0.775346/topol.top 0.775346 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.768572
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.768572/ffbonded.itp nRep80/H_0.768572/ffnonbonded.itp nRep80/H_0.768572/topol.top 0.768572 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.761858
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.761858/ffbonded.itp nRep80/H_0.761858/ffnonbonded.itp nRep80/H_0.761858/topol.top 0.761858 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.755203
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.755203/ffbonded.itp nRep80/H_0.755203/ffnonbonded.itp nRep80/H_0.755203/topol.top 0.755203 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.748606
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.748606/ffbonded.itp nRep80/H_0.748606/ffnonbonded.itp nRep80/H_0.748606/topol.top 0.748606 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.742066
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.742066/ffbonded.itp nRep80/H_0.742066/ffnonbonded.itp nRep80/H_0.742066/topol.top 0.742066 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.735584
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.735584/ffbonded.itp nRep80/H_0.735584/ffnonbonded.itp nRep80/H_0.735584/topol.top 0.735584 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.729158
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.729158/ffbonded.itp nRep80/H_0.729158/ffnonbonded.itp nRep80/H_0.729158/topol.top 0.729158 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.722789
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.722789/ffbonded.itp nRep80/H_0.722789/ffnonbonded.itp nRep80/H_0.722789/topol.top 0.722789 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.716475
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.716475/ffbonded.itp nRep80/H_0.716475/ffnonbonded.itp nRep80/H_0.716475/topol.top 0.716475 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.710216
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.710216/ffbonded.itp nRep80/H_0.710216/ffnonbonded.itp nRep80/H_0.710216/topol.top 0.710216 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.704011
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.704011/ffbonded.itp nRep80/H_0.704011/ffnonbonded.itp nRep80/H_0.704011/topol.top 0.704011 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.697862
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.697862/ffbonded.itp nRep80/H_0.697862/ffnonbonded.itp nRep80/H_0.697862/topol.top 0.697862 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.691765
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.691765/ffbonded.itp nRep80/H_0.691765/ffnonbonded.itp nRep80/H_0.691765/topol.top 0.691765 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.685722
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.685722/ffbonded.itp nRep80/H_0.685722/ffnonbonded.itp nRep80/H_0.685722/topol.top 0.685722 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.679732
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.679732/ffbonded.itp nRep80/H_0.679732/ffnonbonded.itp nRep80/H_0.679732/topol.top 0.679732 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.673794
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.673794/ffbonded.itp nRep80/H_0.673794/ffnonbonded.itp nRep80/H_0.673794/topol.top 0.673794 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.667908
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.667908/ffbonded.itp nRep80/H_0.667908/ffnonbonded.itp nRep80/H_0.667908/topol.top 0.667908 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.662073
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.662073/ffbonded.itp nRep80/H_0.662073/ffnonbonded.itp nRep80/H_0.662073/topol.top 0.662073 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.65629
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.65629/ffbonded.itp nRep80/H_0.65629/ffnonbonded.itp nRep80/H_0.65629/topol.top 0.65629 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.650557
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.650557/ffbonded.itp nRep80/H_0.650557/ffnonbonded.itp nRep80/H_0.650557/topol.top 0.650557 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.644874
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.644874/ffbonded.itp nRep80/H_0.644874/ffnonbonded.itp nRep80/H_0.644874/topol.top 0.644874 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.63924
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.63924/ffbonded.itp nRep80/H_0.63924/ffnonbonded.itp nRep80/H_0.63924/topol.top 0.63924 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.633656
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.633656/ffbonded.itp nRep80/H_0.633656/ffnonbonded.itp nRep80/H_0.633656/topol.top 0.633656 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.628121
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.628121/ffbonded.itp nRep80/H_0.628121/ffnonbonded.itp nRep80/H_0.628121/topol.top 0.628121 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.622634
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.622634/ffbonded.itp nRep80/H_0.622634/ffnonbonded.itp nRep80/H_0.622634/topol.top 0.622634 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.617195
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.617195/ffbonded.itp nRep80/H_0.617195/ffnonbonded.itp nRep80/H_0.617195/topol.top 0.617195 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.611803
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.611803/ffbonded.itp nRep80/H_0.611803/ffnonbonded.itp nRep80/H_0.611803/topol.top 0.611803 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.606459
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.606459/ffbonded.itp nRep80/H_0.606459/ffnonbonded.itp nRep80/H_0.606459/topol.top 0.606459 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.601161
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.601161/ffbonded.itp nRep80/H_0.601161/ffnonbonded.itp nRep80/H_0.601161/topol.top 0.601161 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.595909
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.595909/ffbonded.itp nRep80/H_0.595909/ffnonbonded.itp nRep80/H_0.595909/topol.top 0.595909 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.590704
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.590704/ffbonded.itp nRep80/H_0.590704/ffnonbonded.itp nRep80/H_0.590704/topol.top 0.590704 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.585543
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.585543/ffbonded.itp nRep80/H_0.585543/ffnonbonded.itp nRep80/H_0.585543/topol.top 0.585543 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.580428
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.580428/ffbonded.itp nRep80/H_0.580428/ffnonbonded.itp nRep80/H_0.580428/topol.top 0.580428 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.575358
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.575358/ffbonded.itp nRep80/H_0.575358/ffnonbonded.itp nRep80/H_0.575358/topol.top 0.575358 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.570332
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.570332/ffbonded.itp nRep80/H_0.570332/ffnonbonded.itp nRep80/H_0.570332/topol.top 0.570332 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.56535
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.56535/ffbonded.itp nRep80/H_0.56535/ffnonbonded.itp nRep80/H_0.56535/topol.top 0.56535 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.560411
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.560411/ffbonded.itp nRep80/H_0.560411/ffnonbonded.itp nRep80/H_0.560411/topol.top 0.560411 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.555515
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.555515/ffbonded.itp nRep80/H_0.555515/ffnonbonded.itp nRep80/H_0.555515/topol.top 0.555515 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.550663
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.550663/ffbonded.itp nRep80/H_0.550663/ffnonbonded.itp nRep80/H_0.550663/topol.top 0.550663 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.545852
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.545852/ffbonded.itp nRep80/H_0.545852/ffnonbonded.itp nRep80/H_0.545852/topol.top 0.545852 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.541084
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.541084/ffbonded.itp nRep80/H_0.541084/ffnonbonded.itp nRep80/H_0.541084/topol.top 0.541084 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.536357
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.536357/ffbonded.itp nRep80/H_0.536357/ffnonbonded.itp nRep80/H_0.536357/topol.top 0.536357 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.531672
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.531672/ffbonded.itp nRep80/H_0.531672/ffnonbonded.itp nRep80/H_0.531672/topol.top 0.531672 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.527027
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.527027/ffbonded.itp nRep80/H_0.527027/ffnonbonded.itp nRep80/H_0.527027/topol.top 0.527027 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.522423
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.522423/ffbonded.itp nRep80/H_0.522423/ffnonbonded.itp nRep80/H_0.522423/topol.top 0.522423 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.51786
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.51786/ffbonded.itp nRep80/H_0.51786/ffnonbonded.itp nRep80/H_0.51786/topol.top 0.51786 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.513336
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.513336/ffbonded.itp nRep80/H_0.513336/ffnonbonded.itp nRep80/H_0.513336/topol.top 0.513336 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.508851
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.508851/ffbonded.itp nRep80/H_0.508851/ffnonbonded.itp nRep80/H_0.508851/topol.top 0.508851 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.504406
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.504406/ffbonded.itp nRep80/H_0.504406/ffnonbonded.itp nRep80/H_0.504406/topol.top 0.504406 hotResidues.input hotInteractions.input
	mkdir nRep80/H_0.5
	./modifyHamiltonian ffbonded.itp ffnonbonded.itp topol.top nRep80/H_0.5/ffbonded.itp nRep80/H_0.5/ffnonbonded.itp nRep80/H_0.5/topol.top 0.5 hotResidues.input hotInteractions.input
